### ISSUE TITLE
Enabling plugin changes formatting of embedded CSS, even with embeddedCssTags: []

### ISSUE THREAD

**Issue by jming422** [Sec-ant/prettier-plugin-embed#88]
I've been using Prettier's native embedded formatting for CSS template strings for a while; now I am installing `prettier-plugin-embed` in order to get embedded formatting for SQL, etc. However, enabling this plugin is changing the formatting of my previously Prettier'd CSS template strings.

Under the CSS section, the README says:

> This can override the native formatting behavior for embedded CSS language. If you want to keep the native behavior, set `embeddedCssComments` or `embeddedCssTags` to `[]` or other values.

I've tried setting both of these options to `[]`, but still the difference in behavior persists. For example:

```diff
   const menuDropdownStyle = css`
     display: flex;
-    ${width ? `min-width: ${width};` : ''}
-    align-items: center;
+    ${width ? `min-width: ${width};` : ''} align-items: center;
```

On native Prettier, `align-items: center;` remained on a separate line after the interpolation, but after enabling this plugin, it is moved onto the same line as the interpolation, even with `embeddedCssTags` set to `[]`. The only way I can get the same behavior as before is by not using the `prettier-plugin-embed` plugin.

For this particular example, moving the semicolon from inside the interpolation to after it results in a format output like I want, but diffs like this occur many times throughout my codebase, and I don't want to change all these cases when native Prettier was perfectly fine for them.

Is there any way I can get the native embedded CSS behavior while still having `prettier-plugin-embed` enabled so that I can use it for other embedded languages?

Thanks in advance!

_____

**.prettierrc.yml**
```yml
printWidth: 120
singleQuote: true
trailingComma: es5
plugins:
  - prettier-plugin-sql-cst
  - prettier-plugin-embed
embeddedNoopComments:
  - nofmt
embeddedSqlTags:
  - psql
  - dsql
embeddedCssComments: []
embeddedCssTags: []
embeddedSqlPlugin: prettier-plugin-sql-cst
embeddedOverrides: .prettier-embedded.json
```

**.prettier-embedded.json**
```json
[
  {
    "tags": ["psql"],
    "options": { "parser": "postgresql", "sqlParamTypes": ["$nr"] }
  },
  {
    "tags": ["dsql"],
    "options": { "parser": "bigquery", "sqlParamTypes": [":name"] }
  }
]
```

**Comment by Sec-ant** [comment]
I just pushed a fix, would you please check if the test package in https://github.com/Sec-ant/prettier-plugin-embed/pull/89#issuecomment-1962320006 works as expected?

**Comment by jming422** [comment]
On [this build](https://ci.codesandbox.io/status/Sec-ant/prettier-plugin-embed/pr/89/builds/476791) I get:
```
> prettier --check --config .prettierrc.yml "**/*.{js,json,yml,md,css}"

Checking formatting...
.eslintrc.json
[error] Invalid embeddedEsComments value. Expected an array of a string, but received undefined.
```

If I set this to e.g. an empty array and try again, it has the same error for `embeddedEsTags`, then `embeddedGlslComments`, and I stopped there 😅

**Comment by Sec-ant** [comment]
Oh, bummer! Sorry for the inconvenience. I've to take a while to reconsider this problem. If this cannot be fixed in a patch release, I may have to remove `identifiers`-named options entirely in `v0.5` to fix this problem.

As a workaround, in the current version (v0.4.14), instead of setting `embeddedCssComments` and `embeddedCssTags` to `[]`, you can set the deprecated option `embeddedCssIdentifiers` to `[]` and it should be able to work as expected, that is using the built-in embedded css formatter.

**Comment by jming422** [comment]
Thanks for looking into it so thoroughly 😄 

Interestingly, `embeddedCssIdentifiers` also does not stop these diffs. With this `.prettierrc.yml`:
```
printWidth: 120
singleQuote: true
trailingComma: es5
plugins:
  - prettier-plugin-embed
embeddedNoopComments:
  - nofmt
embeddedCssIdentifiers: []
```

the diff in my original description still is made! While with this one:
```
printWidth: 120
singleQuote: true
trailingComma: es5
```

It remains the same. I made sure that embedded CSS is working at all on native prettier with this config by messing with the indentation, and it did show up on `npx prettier --check`. Another bit I found (I'm not sure if its helpful) is that on native Prettier, both ways of writing the diff in the issue description are accepted and left unchanged, while with the plugin enabled only the second/green way is accepted.

**Comment by Sec-ant** [comment]
I don't know why the `embeddedCssIdentifiers` workaround doesn't work, but I made another attempt to fix this issue. Please try the latest package in that PR. (I tested locally with small samples but I need a confirmation from real life projects)

> Another bit I found (I'm not sure if its helpful) is that on native Prettier, both ways of writing the diff in the issue description are accepted and left unchanged, while with the plugin enabled only the second/green way is accepted.

Yeah this is another problem that is also addressed in that PR. You can see 2 commits I made and one of them is to address that problem.

**Comment by jming422** [comment]
On [this build (`eafbf1b1`)](https://ci.codesandbox.io/status/Sec-ant/prettier-plugin-embed/pr/89/builds/476974), using my regular config, I get the same output as in https://github.com/Sec-ant/prettier-plugin-embed/issues/88#issuecomment-1964687908

```
> prettier --check --config .prettierrc.yml "**/*.{js,json,yml,md,css}"

Checking formatting...
.eslintrc.json
[error] Invalid embeddedEsComments value. Expected an array of a string, but received undefined.
```

With `.prettierrc.yml`
```yml
printWidth: 120
singleQuote: true
trailingComma: es5
plugins:
  - prettier-plugin-embed
embeddedNoopComments:
  - nofmt
embeddedCssComments: []
embeddedCssTags: []
```

_____

But! I went ahead and set the options for every language to `[]` to make all these undefined errors go away, and it worked! 

```
❯ npx prettier --check --config .prettierrc.yml "**/*.js"
Checking formatting...
All matched files use Prettier code style!
```

I introduced a formatting error in one of my embedded CSS tags, and it was correctly identified as well, so the embedded formatting is working as desired 🎉 

`.prettierrc.yml`
```yml
printWidth: 120
singleQuote: true
trailingComma: es5
plugins:
  - prettier-plugin-embed
embeddedNoopComments:
  - nofmt
embeddedCssComments: []
embeddedCssTags: []
embeddedEsComments: []
embeddedEsTags: []
embeddedGlslComments: []
embeddedGlslTags: []
embeddedGraphqlComments: []
embeddedGraphqlTags: []
embeddedHtmlComments: []
embeddedHtmlTags: []
embeddedIniComments: []
embeddedIniTags: []
embeddedJavaComments: []
embeddedJavaTags: []
embeddedJsonComments: []
embeddedJsonTags: []
embeddedJsonataComments: []
embeddedJsonataTags: []
embeddedLatexComments: []
embeddedLatexTags: []
embeddedMarkdownComments: []
embeddedMarkdownTags: []
embeddedNginxComments: []
embeddedNginxTags: []
embeddedNoopTags: []
embeddedPegjsComments: []
embeddedPegjsTags: []
embeddedPhpComments: []
embeddedPhpTags: []
embeddedPrismaComments: []
embeddedPrismaTags: []
embeddedPropertiesComments: []
embeddedPropertiesTags: []
embeddedPugComments: []
embeddedPugTags: []
embeddedRubyComments: []
embeddedRubyTags: []
embeddedShComments: []
embeddedShTags: []
embeddedSqlComments: []
embeddedSqlTags: []
embeddedTomlComments: []
embeddedTomlTags: []
embeddedTsComments: []
embeddedTsTags: []
embeddedXmlComments: []
embeddedXmlTags: []
embeddedYamlComments: []
embeddedYamlTags: []
```

_____

To confirm that it still works with other languages enabled, I went back to my desired `.prettierrc.yml`, except with `*Tags` and `*Comments` I'm not using set to `[]`:

```yml
printWidth: 120
singleQuote: true
trailingComma: es5
plugins:
  - prettier-plugin-sql-cst
  - prettier-plugin-embed
embeddedNoopComments:
  - nofmt
embeddedSqlTags:
  - psql
  - dsql
embeddedSqlPlugin: prettier-plugin-sql-cst
embeddedSqlParser: postgresql
embeddedOverrides: >
  [
    { "tags": ["psql"], "options": { "parser": "postgresql", "sqlParamTypes": ["$nr"] } },
    { "tags": ["dsql"], "options": { "parser": "bigquery", "sqlParamTypes": [":name"] } }
  ]
embeddedCssComments: []
embeddedCssTags: []
embeddedSqlComments: []
embeddedEsComments: []
embeddedEsTags: []
embeddedGlslComments: []
embeddedGlslTags: []
embeddedGraphqlComments: []
embeddedGraphqlTags: []
embeddedHtmlComments: []
embeddedHtmlTags: []
embeddedIniComments: []
embeddedIniTags: []
embeddedJavaComments: []
embeddedJavaTags: []
embeddedJsonComments: []
embeddedJsonTags: []
embeddedJsonataComments: []
embeddedJsonataTags: []
embeddedLatexComments: []
embeddedLatexTags: []
embeddedMarkdownComments: []
embeddedMarkdownTags: []
embeddedNginxComments: []
embeddedNginxTags: []
embeddedNoopTags: []
embeddedPegjsComments: []
embeddedPegjsTags: []
embeddedPhpComments: []
embeddedPhpTags: []
embeddedPrismaComments: []
embeddedPrismaTags: []
embeddedPropertiesComments: []
embeddedPropertiesTags: []
embeddedPugComments: []
embeddedPugTags: []
embeddedRubyComments: []
embeddedRubyTags: []
embeddedShComments: []
embeddedShTags: []
embeddedTomlComments: []
embeddedTomlTags: []
embeddedTsComments: []
embeddedTsTags: []
embeddedXmlComments: []
embeddedXmlTags: []
embeddedYamlComments: []
embeddedYamlTags: []
```

This config works perfectly for my whole project on `eafbf1b1`, CSS, SQL, all working!

Only thing left that would help me is to be able to remove all those other langauges' Comments/Tags settings to `[]` that I don't actually care about
